import { pageOf } from "../../util/page";

export=pageOf(function(me){
  return {
    title:"我的推广二维码",
    element:{
      type:"div",
      children:[
        {
          type:"img",
          attr:{
            src:pathOf("./Logo.png")
          },
          style:{
            display:"inline-block",
            width:"20%",
            margin:"10%",
            background:"gray"
          }
        },
        {
          type:"div",
          style:{
            "text-align":"center"
          },
          text:"金点卡管家"
        },
        {
          type:"div",
          style:{
            "text-align":"center",
            position:"absolute",
            width:"100%",
            bottom:"10%"
          },
          children:[
            {
              type:"img",
              attr:{
                src:pathOf("./二维码.png")
              },
              style:{
                margin:"10%"
              },
            },
            {
              type:"div",
              text:`推荐人:张XX`
            },
            {
              type:"div",
              text:`推荐人手机号：13200010001`
            }
          ]
        }
      ]
    }
  }
})